name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: false
        tags: |
          fabricioveronez/kube-news:${{github.run_number}}
          fabricioveronez/kube-news:latest                

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.16.1
      with:
        image-ref: fabricioveronez/kube-news:${{github.run_number}}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Configurar as credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update KubeConfig
      shell: bash
      run: |
        aws eks update-kubeconfig --name imersao-eks --region us-east-1
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./kube-news/k8s/deployment.yaml
        images: |
          fabricioveronez/kube-news:${{github.run_number}}
